StylesPath = .vale/styles
MinAlertLevel = suggestion

Packages = Google, write-good

[*.{md,txt}]
BasedOnStyles = Vale, Google, write-good

[src/infrastructure/db/*.ts]
# Lint spelling and formatting inside database seed data rows
BasedOnStyles = Vale
